gollum015
gollum016
gollum017
WORLD_SIZE=9
MATER_PORT=31319
MASTER_ADDR=gollum015
export SLURM_LOCAL_SCRATCH=/scratch/xqding/671319
export PMI_TIME=4000
export SLURM_LOCAL_SCRATCH
export BASH_ENV=/etc/profile.d/module.sh
export OMP_NUM_THREADS=1
export OPENMM_CPU_THREADS=1
I am rank: 0 out of a world size of 9
I am rank: 1 out of a world size of 9
I am rank: 2 out of a world size of 9
I am rank: 8 out of a world size of 9
I am rank: 4 out of a world size of 9
I am rank: 5 out of a world size of 9
I am rank: 6 out of a world size of 9
I am rank: 3 out of a world size of 9
I am rank: 7 out of a world size of 9
export SLURM_LOCAL_SCRATCH
